"""add signal_class to news_articles

Revision ID: d4b380885363
Revises: 
Create Date: 2026-05-16 02:10:15.645590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b380885363'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('signal_class', sa.String(), nullable=True))
    op.drop_index('idx_news_ingested_at', table_name='news_articles')
    op.drop_index('idx_news_published_at', table_name='news_articles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_news_published_at', 'news_articles', [sa.text('published_at DESC')], unique=False)
    op.create_index('idx_news_ingested_at', 'news_articles', [sa.text('ingested_at DESC')], unique=False)
    op.drop_column('news_articles', 'signal_class')
    # ### end Alembic commands ###
