"""add image_url to news_articles

Revision ID: fcc98f777923
Revises: d4b380885363
Create Date: 2026-05-16 02:24:01.476295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "fcc98f777923"
down_revision: Union[str, None] = "d4b380885363"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("news_articles", sa.Column("image_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("news_articles", "image_url")
    # ### end Alembic commands ###
